### get tooele tech route
GET http://localhost:3000/ttech HTTP/1.1

### get the root path 
GET http://localhost:3000/ HTTP/1.1

### get all students
GET http://localhost:3000/students HTTP/1.1

### get one student
GET http://localhost:3000/students/67f5527fb2e44707d17ec876 HTTP/1.1

### create student
POST http://localhost:3000/students HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jeff",
    "lastName": "Phill",
    "email": "danthemagicman@gmail.com",
    "age": 42,
    "currentCollage": "none"
}

### update student
POST http://localhost:3000/students/update/67f5527fb2e44707d17ec876 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Clark",
    "email": "max@gmail.com",
    "age": 32,
    "currentCollage": "Harvard"
}

### delete student
DELETE http://localhost:3000/students/delete/67f95448f4a96a80491b99bb HTTP/1.1